#!/bin/sh

set -ex

virtualenv py3 --python=/usr/bin/python3
. py3/bin/activate
pip3 install --upgrade meson ninja

export MESON_SOURCE_ROOT=$(pwd)
export MESON_BUILD_ROOT=$MESON_SOURCE_ROOT/build

doxygen $MESON_SOURCE_ROOT/Doxyfile
