#!/bin/sh

set -x

# decrypt and add key to ssh-agent
eval $(ssh-agent -s)
keyfile=build/arma-id-rsa
openssl aes-256-cbc -K $encrypted_3ea07b9ba991_key -iv $encrypted_3ea07b9ba991_iv
	-in arma-id-rsa.enc -out $keyfile -d
chmod 600 $keyfile
ssh-add $keyfile

# push to gh-pages branch
repo_url=git@github.com:igankevich/arma 
git clone --branch=gh-pages $repo_url gh-pages
cd gh-pages
git rm -rf .
mv ../build/html/* .
git add --all
git config user.name "Travis CI"
git config user.email "travis@travis-ci.org"
git commit -m "Deploy to gh-pages."
git push $repo_url gh-pages
