#ifndef PROFILE_COUNTERS_HH
#define PROFILE_COUNTERS_HH

#include "profile.hh"

#define CNT_HARTS_G1 0
#define CNT_HARTS_G2 1
#define CNT_HARTS_FFT 2
#define CNT_HARTS_COPY_TO_HOST 3
#define CNT_COPY_TO_HOST 4
#define CNT_WRITE_SURFACE 5
#define CNT_BSC_COPY 6
#define CNT_BSC_MARSHALLING 7

#endif // PROFILE_COUNTERS_HH
