#ifndef PROFILE_COUNTERS_HH
#define PROFILE_COUNTERS_HH

#include "profile.hh"

#define CNT_WINDOWFUNC 0
#define CNT_SECONDFUNC 1
#define CNT_FFT 2
#define CNT_DEVTOHOST_COPY 3
#define CNT_COPY_TO_HOST 4
#define CNT_WRITE_SURFACE 5

#endif // PROFILE_COUNTERS_HH
